
import React, { useState } from 'react';
import * as geminiService from '../services/geminiService';
import LoadingSpinner from './LoadingSpinner';
import { ImageIcon } from './IconComponents';

type AspectRatio = "1:1" | "16:9" | "9:16" | "4:3" | "3:4";

const ImageGenPanel: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('1:1');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const aspectRatios: AspectRatio[] = ["1:1", "16:9", "9:16", "4:3", "3:4"];

  const handleGenerate = async () => {
    if (!prompt.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setGeneratedImage(null);

    try {
      const imageUrl = await geminiService.generateImage(prompt, aspectRatio);
      setGeneratedImage(imageUrl);
    } catch (err) {
      console.error("ImageGenPanel Error:", err);
      setError("Image generation failed. Your prompt might have violated safety policies, or there could be a network issue. Please revise your prompt or try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="h-full flex flex-col">
      <h2 className="text-2xl font-bold text-cyan-400 mb-4">Image Generation</h2>
      <p className="text-gray-400 mb-6">
        Create high-quality images from text descriptions using the Imagen model.
      </p>
      
      <div className="space-y-4 mb-6">
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g., A photorealistic image of a scientist discovering a glowing blue plant in a futuristic lab."
          className="w-full bg-gray-800 border border-gray-700 rounded-lg p-3 focus:ring-2 focus:ring-cyan-500 focus:outline-none text-gray-200 h-24 resize-none"
          disabled={isLoading}
        />
        <div className="flex flex-col sm:flex-row items-center gap-4">
            <div className="w-full sm:w-auto">
                <label htmlFor="aspectRatio" className="block text-sm font-medium text-gray-300 mb-2">Aspect Ratio</label>
                <select
                    id="aspectRatio"
                    value={aspectRatio}
                    onChange={(e) => setAspectRatio(e.target.value as AspectRatio)}
                    className="bg-gray-800 border border-gray-700 rounded-lg p-3 focus:ring-2 focus:ring-cyan-500 focus:outline-none text-gray-200 w-full"
                    disabled={isLoading}
                >
                    {aspectRatios.map(ar => <option key={ar} value={ar}>{ar}</option>)}
                </select>
            </div>
            <button
              onClick={handleGenerate}
              disabled={isLoading || !prompt.trim()}
              className="bg-cyan-500 w-full sm:w-auto self-end text-white p-3 rounded-lg disabled:bg-gray-600 disabled:cursor-not-allowed hover:bg-cyan-400 transition-colors flex items-center justify-center gap-2 mt-2 sm:mt-0"
            >
              <ImageIcon />
              <span>Generate Image</span>
            </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto bg-gray-800/50 rounded-lg p-6 border border-gray-700 flex items-center justify-center">
        {isLoading && <LoadingSpinner text="Generating image..." />}
        {error && <p className="text-red-400">{error}</p>}
        {generatedImage && (
          <div className="flex flex-col items-center gap-4">
            <img 
              src={generatedImage} 
              alt="Generated by AI" 
              className="max-w-full max-h-[60vh] rounded-lg shadow-lg"
            />
            <a 
                href={generatedImage} 
                download="generated-image.jpg"
                className="bg-gray-700 text-gray-200 py-2 px-4 rounded-lg hover:bg-gray-600 transition-colors"
            >
                Download Image
            </a>
          </div>
        )}
        {!isLoading && !generatedImage && !error && (
            <div className="text-center text-gray-500">
                <p>Your generated image will appear here.</p>
            </div>
        )}
      </div>
    </div>
  );
};

export default ImageGenPanel;
